# This action will run after a release is created and published on github.
# It will attempt to publish that release to NPM.

name: Viro React NPM publish
on:
  release:
    types: [published]
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - uses: JS-DevTools/npm-publish@v3
        with:
          token: ${{ secrets.NPM_TOKEN }}
